### ISSUE TITLE
Do we want a cron job to trigger this build?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/drd#1]
A cron job that runs the POST request given here: https://registry.hub.docker.com/u/rocker/drd/settings/triggers/

can be used to trigger daily builds if we like.  Thoughts?

**Comment by eddelbuettel** [comment]
Recall how we wanted to be prudent with cycles :) 

So so far I triggered it with manual updates to Readme.md as you can see from its low. 

I have not run this daily.  Daily strikes me as excessive.   Weekly seems like a good compromise.

**Comment by cboettig** [comment]
Sure, the cron job could be whatever interval you like of course.  As I
suppose I demonstrated with travis though, I'm not too worried about free
cycles; heck, it says on the build triggers:

We throttle build requests so that you can't overload the system. If you
already have a build request pending, or if you submitted too many requests
in a short period of time, your request will be ignored. See the trigger
logs below to see if your request was created or not.

**Comment by eddelbuettel** [comment]
I can't commit to be able to look after failures daily, but if you want to give it a shot.

I guess you decided it all already anyway while I was a few thousand feet up in the air...

**Comment by cboettig** [comment]
We've had a cron job on this, mostly works pretty well, so we can close this I think.
