### ISSUE TITLE
Can't build igraph package

### ISSUE THREAD

**Issue by artemklevtsov** [rocker-org/drd#4]
Hi.

To reproduce:

``` bash
docker run -ti rocker/drd:latest Rscript -e 'install.packages("igraph")' 
```

Build process stopped with the following error:

``` bash
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
```

Note: with `RDscript` the package installed successful.

Regards,
Artem

**Comment by eddelbuettel** [comment]
That is a combination of your usage error and my documentation.  

Both the drd and r-devel containers still include R (as in R-release) via the .deb package for convenience _but not as a full dev environment_ while focusing on RD (as in R-devel) for development and testing.

So in essence you first tested the wrong R, and then the right one with which everything works.

No issue here, so I close this.  Ok?
