### ISSUE TITLE
train function in caret package

### ISSUE THREAD

**Issue by elahech** [rocker-org/drd#5]
Hi all,
I already installed caret package in R but when I want to use train function in this package I face this error:

    Loading required package: class
    Error in comp(expr, env = envir, options = list(suppressUndefined = TRUE)) : 
    could not find function "mayCallBrowser"
I'm using version 3.2.5. Does anyone have any idea?! I need this train function for a feature selection task and I cannot understand the problem. 
Thanks for any help!

Elahe

**Comment by eddelbuettel** [comment]
This is not the correct forum for this question.
