### ISSUE TITLE
About building with GitHub Actions

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/drd#9]
Hi, there are a few concerns about building with GitHub Actions.

1. Since you don't specify the branch to be pushed as a trigger, rocker/drd:latest will be published even if you push to a non-default branch. I think it would be better to restrict the triggered branch. https://docs.github.com/es/actions/reference/events-that-trigger-workflows
2. Since the PR trigger also pushes `rocker/drd:latest`, the contents before being merged into the default branch will be published as `rocker/drd:latest`. I think it is better to set it so that it will not be pushed if it is triggered by `pull_request`.
3. I think that it is supposed to be automatically executed by schedule as the main trigger, but if the repository is not changed for 60 days, the workflow will be invalidated. Instead, set the base image to something like `r-base: 4.1.1@sha256:7a55c99a48f8759a209c21c06cb2c44ec52d7bbe472957e31e5c29d497484db2` and use dependabot to create a PR every time the base image is updated and it will be built when the PR is merged. It may be convenient to do so because the update of the base image can be reflected immediately. https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow

https://github.com/rocker-org/drd/blob/5f81f2a205a2e9739c1b43735861ae84291e66c8/.github/workflows/docker.yaml#L3-L5

https://github.com/rocker-org/drd/blob/5f81f2a205a2e9739c1b43735861ae84291e66c8/.github/workflows/docker.yaml#L33-L34

https://github.com/rocker-org/drd/blob/5f81f2a205a2e9739c1b43735861ae84291e66c8/Dockerfile#L4

I think I can send these changes as a pull request if you like.

**Comment by eddelbuettel** [comment]
Thanks for the feedback  but I am fine with how things are.  These repos tend to not have branches.

**Comment by eitsupi** [comment]
Then feel free to close this issue.

**Comment by eddelbuettel** [comment]
I have to think about the 'sixty days to stale' issue (but no, I do not want to engage dependabot).  That may be a new problem.

Worst case I can fall back to building here (I still have the same local cronjob) and push ...
